# 2018/2019 - Task List 2

1. Visualize (pmf, mean, variance) of pseudo random number generators (parametrized) that follows distributions:

    - Single gaussian 
    - Two combined gaussian distributions 
    - N combined gaussian distributions 


2. Student applied for 9 faculties, acceptance chance for each faculty was 0.01. Unfortunately student was not accepted to any. What is the probability of that situation? Write a function that will solve that problem (parametrized), use exact method and binomials based solution with parameterized number of trials (binomial)

3. Solve previous task taking into account that acceptance chance for each faculty was different  (multinomial)


## Required imports

In [6]:
%matplotlib inline
import pyro
import torch
import numpy as np
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML

# Binomial sampling

In [29]:
m = pyro.distributions.Binomial(1, torch.Tensor(9*[0.01]))
m.sample()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
m = pyro.distributions.Binomial(1, torch.Tensor(5*[0.5]))
m.sample()

tensor([1., 1., 1., 0., 1.])

In [42]:
m = pyro.distributions.Binomial(1, torch.Tensor(5*[0.5]))
m.log_prob(torch.Tensor([1]))

tensor([-0.6931, -0.6931, -0.6931, -0.6931, -0.6931])

# Multinomial sampling

In [38]:
m = pyro.distributions.Multinomial(1, torch.Tensor([0 , .2, .8, 1]))
m.sample()

tensor([0., 1., 0., 0.])

## Task 1

In [13]:
## Insert solution here

## Task 2

In [14]:
## Insert solution here

# Task 3

In [ ]:
## Insert solution here